import { TokenBudgetManager } from '../mcp/token-budget.js';

export interface FileMetric {
  path: string;
  folder: string;
  naiveTokens: number;
  interfaceTokens: number;
  skeletonTokens: number;
  dependencyTokens: number;
  interfaceSaving: number;
  skeletonSaving: number;
}

export class ReportGenerator {
  constructor(private repoName: string) {}

  generateMarkdown(metrics: FileMetric[]): string {
    const totalNaive = metrics.reduce((acc, m) => acc + m.naiveTokens, 0);
    const totalSkeleton = metrics.reduce((acc, m) => acc + m.skeletonTokens, 0);
    const avgSaving = totalNaive > 0 ? Math.floor(((totalNaive - totalSkeleton) / totalNaive) * 100) : 0;

    // Folder aggregation
    const folders: Record<string, FileMetric[]> = {};
    for (const m of metrics) {
      if (!folders[m.folder]) folders[m.folder] = [];
      folders[m.folder].push(m);
    }

    let md = `# 🗜️ TokenZip Efficiency Audit: ${this.repoName}\n`;
    md += `*Generated on: ${new Date().toLocaleDateString()}*\n\n`;

    md += `## 📊 Executive Summary\n`;
    md += `| Metric | Value |\n`;
    md += `| :--- | :--- |\n`;
    md += `| **Total Files Analyzed** | ${metrics.length} |\n`;
    md += `| **Naive Token Footprint** | ${totalNaive.toLocaleString()} |\n`;
    md += `| **Optimized Footprint (Skeleton)** | ${totalSkeleton.toLocaleString()} |\n`;
    md += `| **Aggregate Repository Saving** | **${avgSaving}%** 🚀 |\n\n`;

    md += `---\n\n`;
    md += `## 📂 Folder-Level Breakdown\n`;
    md += `| Folder Path | Files | Naive (Avg) | Interface Saving | Skeleton Saving | Efficiency |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;

    const folderRows = Object.entries(folders).map(([name, files]) => {
      const fNaive = files.reduce((acc, f) => acc + f.naiveTokens, 0);
      const fInterface = files.reduce((acc, f) => acc + f.interfaceTokens, 0);
      const fSkeleton = files.reduce((acc, f) => acc + f.skeletonTokens, 0);
      
      const iSaving = fNaive > 0 ? Math.floor(((fNaive - fInterface) / fNaive) * 100) : 0;
      const sSaving = fNaive > 0 ? Math.floor(((fNaive - fSkeleton) / fNaive) * 100) : 0;
      
      let status = '🔴 Low';
      if (sSaving > 70) status = '🟢 Excellent';
      else if (sSaving > 40) status = '🟡 Moderate';

      return `| \`${name}\` | ${files.length} | ${Math.round(fNaive/files.length).toLocaleString()} | ${iSaving}% | ${sSaving}% | ${status} |`;
    });

    md += folderRows.join('\n') + '\n\n';

    md += `---\n\n`;

    // Statistical Percentiles
    const interfaceSavings = metrics.map(m => m.interfaceSaving);
    const skeletonSavings = metrics.map(m => m.skeletonSaving);

    md += `## 📈 Statistical Distribution\n`;
    md += `| Percentile | Interface Saving | Skeleton Saving |\n`;
    md += `| :--- | :--- | :--- |\n`;
    md += `| **P50 (Median)** | ${this.getPercentile(interfaceSavings, 50)}% | ${this.getPercentile(skeletonSavings, 50)}% |\n`;
    md += `| **P95** | ${this.getPercentile(interfaceSavings, 95)}% | ${this.getPercentile(skeletonSavings, 95)}% |\n`;
    md += `| **P97.5** | ${this.getPercentile(interfaceSavings, 97.5)}% | ${this.getPercentile(skeletonSavings, 97.5)}% |\n\n`;

    md += `---\n\n`;
    md += `## 🚀 Best Savings (Top 10)\n`;
    md += `| File Path | Naive Tokens | Interface Saving | Skeleton Saving | Efficiency |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;

    const bestFiles = [...metrics].sort((a, b) => b.skeletonSaving - a.skeletonSaving).slice(0, 10);
    md += bestFiles.map(m => {
      return `| \`${m.path}\` | ${m.naiveTokens.toLocaleString()} | ${m.interfaceSaving}% | ${m.skeletonSaving}% | 🟢 |`;
    }).join('\n') + '\n\n';

    md += `## 📉 Worst Savings (Bottom 10)\n`;
    md += `| File Path | Naive Tokens | Interface Saving | Skeleton Saving | Efficiency |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;

    const worstFiles = [...metrics].sort((a, b) => a.skeletonSaving - b.skeletonSaving).slice(0, 10);
    md += worstFiles.map(m => {
      return `| \`${m.path}\` | ${m.naiveTokens.toLocaleString()} | ${m.interfaceSaving}% | ${m.skeletonSaving}% | 🔴 |`;
    }).join('\n') + '\n\n';

    md += `--- \n*Generated by TokenZip*`;

    return md;
  }

  private getPercentile(arr: number[], p: number): number {
    if (arr.length === 0) return 0;
    const sorted = [...arr].sort((a, b) => a - b);
    const index = Math.floor((p / 100) * (sorted.length - 1));
    return sorted[index];
  }

  generateCSV(metrics: FileMetric[]): string {
    const header = 'Filepath,Folder,Naive_Tokens,Interface_Tokens,Skeleton_Tokens,Dependency_Tokens,Interface_Saving_Pct,Skeleton_Saving_Pct\n';
    const rows = metrics.map(m => {
      return `"${m.path}","${m.folder}",${m.naiveTokens},${m.interfaceTokens},${m.skeletonTokens},${m.dependencyTokens},${m.interfaceSaving},${m.skeletonSaving}`;
    });
    return header + rows.join('\n');
  }
}
